# This configuration will automatically create docker images based on conventions
# Then on docker hub "lightningcn/bitcoin" will be pushed:
# - 0.17.1-arm32v7 from Bitcoin/0.17.1/linuxarm32v7.Dockerfile
# - 0.17.1-arm64v8 from Bitcoin/0.17.1/linuxarm64v8.Dockerfile
# - 0.17.1-amd64 from Bitcoin/0.17.1/linuxamd64.Dockerfile
version: 2
jobs:
  build:
    machine: 
      docker_layer_caching: true
    steps: 
      - checkout

  # publish jobs require $DOCKERHUB_USER, $DOCKERHUB_PASS defined
  publish_linuxamd64:
    machine:
      docker_layer_caching: true
    steps:
      - checkout  
      - run:
          command: |
            VERSION=0.17.1
            LATEST_TAG=${CIRCLE_TAG:4} #trim "cn-v" from tag
            sudo docker build --pull -t $DOCKERHUB_REPO:$LATEST_TAG-amd64 -f Bitcoin/0.17.1/linuxamd64.Dockerfile Bitcoin/$VERSION
            sudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
            sudo docker push $DOCKERHUB_REPO:$LATEST_TAG-amd64

  publish_linuxarm64v8:
    machine:
      docker_layer_caching: true
    steps:
      - checkout  
      - run:
          command: |
            VERSION=0.17.1
            LATEST_TAG=${CIRCLE_TAG:4} #trim "cn-v" from tag
            sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset

            sudo docker build --pull -t $DOCKERHUB_REPO:$LATEST_TAG-arm64v8 -f Bitcoin/0.17.1/linuxarm64v8.Dockerfile Bitcoin/$VERSION
            sudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
            sudo docker push $DOCKERHUB_REPO:$LATEST_TAG-arm64v8

  publish_linuxarm32v7:
    machine:
      docker_layer_caching: true
    steps:
      - checkout  
      - run:
          command: |
            VERSION=0.17.1
            LATEST_TAG=${CIRCLE_TAG:4} #trim "cn-v" from tag
            sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset

            sudo docker build --pull -t $DOCKERHUB_REPO:$LATEST_TAG-arm32v7 -f Bitcoin/0.17.1/linuxarm32v7.Dockerfile Bitcoin/$VERSION
            sudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
            sudo docker push $DOCKERHUB_REPO:$LATEST_TAG-arm32v7
  
workflows:
  version: 2
  publish:
    jobs:
      - publish_linuxamd64:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /cn-.+/
      - publish_linuxarm32v7:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /cn-.+/
      - publish_linuxarm64v8:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /cn-.+/
